parameters:


services:
  Bitbucket\API\Http\Listener\OAuth2Listener:
    class: Bitbucket\API\Http\Listener\OAuth2Listener
    arguments: [ ~ ]

  Bitbucket\API\Http\Client:
    class: Bitbucket\API\Http\Client
    calls:
      - [ addListener, [ '@Bitbucket\API\Http\Listener\OAuth2Listener']]

  Bitbucket\API\Api:
    class: Bitbucket\API\Api
    arguments: [ [], '@Bitbucket\API\Http\Client' ]